#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jdependency
Version  : 2.0
Release  : 4
URL      : https://repo1.maven.org/maven2/org/vafer/jdependency/2.0/jdependency-2.0.jar
Source0  : https://repo1.maven.org/maven2/org/vafer/jdependency/2.0/jdependency-2.0.jar
Source1  : https://repo1.maven.org/maven2/org/vafer/jdependency/1.0/jdependency-1.0.jar
Source2  : https://repo1.maven.org/maven2/org/vafer/jdependency/1.0/jdependency-1.0.pom
Source3  : https://repo1.maven.org/maven2/org/vafer/jdependency/1.1/jdependency-1.1.jar
Source4  : https://repo1.maven.org/maven2/org/vafer/jdependency/1.1/jdependency-1.1.pom
Source5  : https://repo1.maven.org/maven2/org/vafer/jdependency/2.0/jdependency-2.0.pom
Source6  : https://repo1.maven.org/maven2/org/vafer/jdependency/2.1.1/jdependency-2.1.1.jar
Source7  : https://repo1.maven.org/maven2/org/vafer/jdependency/2.1.1/jdependency-2.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jdependency-data = %{version}-%{release}
Requires: mvn-jdependency-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jdependency package.
Group: Data

%description data
data components for the mvn-jdependency package.


%package license
Summary: license components for the mvn-jdependency package.
Group: Default

%description license
license components for the mvn-jdependency package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jdependency
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-jdependency/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.0/jdependency-2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.0/jdependency-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.0/jdependency-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.1/jdependency-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/1.1/jdependency-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.0/jdependency-2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.1.1
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.1.1/jdependency-2.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.1.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/vafer/jdependency/2.1.1/jdependency-2.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/vafer/jdependency/1.0/jdependency-1.0.jar
/usr/share/java/.m2/repository/org/vafer/jdependency/1.0/jdependency-1.0.pom
/usr/share/java/.m2/repository/org/vafer/jdependency/1.1/jdependency-1.1.jar
/usr/share/java/.m2/repository/org/vafer/jdependency/1.1/jdependency-1.1.pom
/usr/share/java/.m2/repository/org/vafer/jdependency/2.0/jdependency-2.0.jar
/usr/share/java/.m2/repository/org/vafer/jdependency/2.0/jdependency-2.0.pom
/usr/share/java/.m2/repository/org/vafer/jdependency/2.1.1/jdependency-2.1.1.jar
/usr/share/java/.m2/repository/org/vafer/jdependency/2.1.1/jdependency-2.1.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jdependency/LICENSE.txt
